#
# Example job using the CircleCI base image to run a CxAST scan
#
# CLI installed through brew
#
# Configuration through environment variables in CircleCI
#
# Documentation:
# https://checkmarx.com/resource/documents/en/34965-68721-checkmarx-one-circleci-integration.html
#

version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: "Run Scan"
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            /home/linuxbrew/.linuxbrew/bin/brew install checkmarx/ast-cli/ast-cli
            /home/linuxbrew/.linuxbrew/Cellar/ast-cli/*/bin/cx \
            scan create \
            -s . \
            --agent CircleCI \
            --project-name $CIRCLE_PROJECT_REPONAME \
            --branch $CIRCLE_BRANCH \
            --base-uri $BASE_URI \
            --tenant $TENANT \
            --client-id $CLIENT_ID \
            --client-secret $CLIENT_SECRET \
            $ADDITIONAL_PARAMS
