#
# Example job using the CLI image to run a CxAST scan
#
# Configuration through environment variables in CircleCI
#
# Documentation:
# https://checkmarx.atlassian.net/wiki/spaces/AST/pages/6142591258/CircleCI
#

version: 2
jobs:
  build:
    docker:
      - image: checkmarx/ast-cli
    steps:
      - checkout
      - run:
          name: "Run Scan"
          command: |
            /app/bin/cx \
            scan create \
            -s . \
            --agent CircleCI \
            --project-name $CIRCLE_PROJECT_REPONAME \
            --branch $CIRCLE_BRANCH \
            --base-uri $BASE_URI \
            --tenant $TENANT \
            --client-id $CLIENT_ID \
            --client-secret $CLIENT_SECRET \
            $ADDITIONAL_PARAMS
