# Documentation:
# https://checkmarx.atlassian.net/wiki/spaces/AST/pages/6142592048/Bitbucket+Pipelines
#

image: checkmarx/ast-cli
 
pipelines:
  default:
    - step:
        script:
          - >-
            /app/bin/cx
            scan create
            -s .
            --agent Bitbucket
            --project-name $BITBUCKET_REPO_SLUG
            --branch $BITBUCKET_BRANCH
            --base-uri $BASE_URI
            --tenant $TENANT
            --client-id $CLIENT_ID
            --client-secret $CLIENT_SECRET
            $ADDITIONAL_PARAMS
