name: Build
on:
  push:
    branches:
      - main
jobs:
  cx-scan:
    name: Run CxAST cli
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@master
        with:
          project_name: sonar-scan
          base_uri: ${{ secrets.BASE_URI }}
          cx_tenant: ${{ secrets.TENANT }}
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          additional_params: --report-format sonar
      - name: Upload results artifact
        uses: actions/upload-artifact@v2
        with: 
          name: results
          path: ./cx_result_sonar.json
  build:
    name: Publish to sonar
    runs-on: ubuntu-latest
    needs: cx-scan
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: results
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.externalIssuesReportPaths=cx_result_sonar.json